# Generated by Django 3.1.3 on 2021-01-05 21:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0003_auto_20210102_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='favourites',
            field=models.ManyToManyField(blank=True, default='none', related_name='fav', to=settings.AUTH_USER_MODEL),
        ),
    ]
