# Generated by Django 3.1.3 on 2020-12-10 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_header_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='header_image',
            new_name='product_image',
        ),
    ]
