# Generated by Django 3.1.3 on 2020-12-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201211_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header_image',
            field=models.ImageField(default="{% static '/blog/Untitled.png' %}", upload_to='images/'),
        ),
    ]
