# Generated by Django 3.1.3 on 2020-12-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20201211_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, default='/static/blog/product2', null=True, upload_to='images/'),
        ),
    ]
