# Generated by Django 3.1.3 on 2020-12-15 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20201211_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Bags', 'Bags'), ('Shoes', 'Shoes'), ('Tops', 'Tops'), ('Jeans', 'Jeans'), ('Pants', 'Pants'), ('Mobile Phones', 'Mobile Phones'), ('HeadPhones', 'HeadPhones')], default='Bags', max_length=100),
        ),
    ]
