# Generated by Django 3.1.3 on 2021-01-03 22:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0013_postorder_postorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='favourites',
            field=models.ManyToManyField(blank=True, default='none', related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
